config/routes.rb
Psp::Application.routes.draw do

  root to: 'states#index'

  resources :leaders

  resources :states do
    resources :leaders
    resource :calendar
    resources :subscriptions
  end

  match "/states/:id/:year/:month/:day/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/email", to: "states#email", as: "state_email"

  match "/states/:id/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"

  match "/states/:id/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/calendars/daily/:year/:month/:day", to: "states#show", as: "daily_calendar"
  match "/states/:id/calendars/weekly/:year/:month/:day", to: "states#show", as: "weekly_calendar"

  match "/states/:id/:year/:month/:day", to: "states#show", as: "state_date"

  mount Refinery::Core::Engine, :at => '/'

end

app/models/leader.rb
class Leader < Hashie::Mash
  disable_warnings

  def setup(data)
    data.each do |key, value|
      self[key] = value
    end
  end

  def state
    UsState.new(state_code)
  end

  def birthday
    unless born_on.blank?
      Date.parse(born_on).strftime("%B %e")
    else
      ""
    end
  end

  def district_residence
    [district, residence].reject{|i|i.blank?}.join(" - ")
  end

  def name
    self['name'] || ""
  end

  def title
    self['title'] || ""
  end

  def email
    self['email'] || ""
  end

  def photo_src
    self['photo_src'] || "placeholder.jpg"
  end

  def twitter_or_name
    return name if twitter.blank?
    twitter_handle
  end

  private

  def twitter_handle
    "@#{twitter.split('/').last}"
  end
end

app/controllers/api/v1/leaders_controller.rb
module Api
  module V1
    class LeadersController < ApplicationController
      respond_to :json

      def index
        @state = State.find_by_code(params[:state_id].upcase)
      end

      def show
        @state = State.find_by_code(params[:state_id].upcase)
        @leader = Member.find(params[:id])
        respond_with @leader
      end

    end
  end
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
  layout "states"

  def index
    @state = UsState.new(params[:state_id])
  end

  def show
    @leader = LeaderFinder.find(params[:id])
    @state = @leader.state
  end

end

app/views/leaders/_legislative_body.html.erb
<div>
  <ul class="thumbnails">
    <% legislative_body.each do |leader| %>
      <li class="span2">
      <%= link_to leader_path(leader.slug), class: "thumbnail" do %>
        <%= image_tag leader.photo_src, class: "thumbnail-leader" %>
        <h4 class="thumbnail-leader"><%= leader.name %></h4>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/leaders/_profile.html.erb
<div class="well">
  <div class="row-fluid">

    <div class="span3">
      <%= image_tag leader.photo_src, class: 'head-shot' %>
      <h2 class="leader-name visible-phone" style="margin-top:0.25em">
        <%= leader.name %> <small><%= leader.title.strip %></small>
      </h2>
    </div>

    <div class="span9">
      <h2 class="leader-name hidden-phone">
        <%= leader.name.strip %> <small><%= leader.title.strip %></small>
      </h2>
      <div class="row-fluid">
        <div class="span8">
          <table class="table table-striped table-bordered table-condensed">
            <%= leader_data_tr(leader.district_residence, "District") if leader.district_residence %>
            <%= leader_data_tr(leader.religion, "Religion") if leader.religion %>
            <%= leader_data_tr(leader.spouse, "Spouse") if leader.spouse %>
            <%= leader_data_tr(leader.family, "Family") if leader.family %>
            <%= leader_data_tr(leader.birthday, "Birthday") if leader.birthday %>
          </table>
        </div>
        <div class="span3" style="padding-left:0.75em">
          <br />
          <div style="text-align:right;padding-left:0.5em">
            <ul class="unstyled">
              <%= content_tag('li', link_to("Website", leader.website)) unless leader.website.blank? %>
              <%= content_tag('li', link_to("Contact", leader[:webform])) unless leader[:webform].blank? %>
              <%= content_tag('li', link_to("Facebook", leader.facebook)) unless leader.facebook.blank? %>
              <%= content_tag('li', link_to("Email", "mailto: #{leader.email}")) unless leader.email.blank? %>
              <%= content_tag('li', link_to("Twitter", leader.twitter)) unless leader[:twitter].blank? %>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/leaders/_profile_email_rss.html.erb
<table cellpadding="20" cellspacing="0" border="0" align="left">
  <tr>
    <td valign="top">
      <br />
      <%= image_tag "http://publicservantsprayer.org#{leader.photo_src}", alt: "Photo of #{leader.name.strip}. (Show images to view)" %>
    </td>
    <td>
      <h2><%= leader.name.strip %> <span style="font-size:14px;color:#333333"><%= leader.title.strip %></span></h2>

      <table width="100%" cellpadding="5" cellspacing="5" border="0" align="left" style="border:1px solid #999999">
        <tr>
          <th>District</th>
          <td><%= leader.district_residence %></td>
        </tr>
        <% unless leader.religion.blank? %>
        <tr>
          <th>Religion</th>
          <td><%= leader.religion %>
        </tr>
      <% end %>
        <tr>
          <th>Spouse</th>
          <td><%= leader.spouse %></td>
        </tr>
        <tr>
          <th>Family</th>
          <td><%= leader.family %></td>
        </tr>
        <% unless leader.birthday.blank? %>
        <tr>
          <th>Birthday</th>
          <td><%= leader.birthday %></td>
        </tr>
        <% end %>
        <tr>
          <td colspan="2">
          <ul>
            <%= content_tag('li', link_to("Website", leader.website)) unless leader.website.blank? %>
            <%= content_tag('li', link_to("Contact", leader[:webform])) unless leader[:webform].blank? %>
            <%= content_tag('li', link_to("Facebook", leader.facebook)) unless leader.facebook.blank? %>
            <%= content_tag('li', link_to("Email", "mailto:#{leader.email}")) unless leader.email.blank? %>
            <%= content_tag('li', link_to("Twitter", leader.twitter)) unless leader[:twitter].blank? %>
          </ul>
          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>

app/views/leaders/index.html.erb
<% content_for :page_title do %>
  <h1 class="page-header"><%= @state.name %> Elected Leaders</h1>
<% end %>

<div class="thumbnail-leaders">
  <h2>U.S. Senate</h2>
  <%= render :partial => 'legislative_body', locals: {legislative_body: @state.us_senate} %>
  <hr />

  <h2>U.S. House</h2>
  <%= render :partial => 'legislative_body', locals: {legislative_body: @state.us_house} %>
  <hr />

  <h2>State Senate</h2>
  <%= render :partial => 'legislative_body', locals: {legislative_body: @state.state_senate} %>
  <hr />

  <h2>State House</h2>
  <%= render :partial => 'legislative_body', locals: {legislative_body: @state.state_house} %>
</div>

app/views/leaders/show.html.erb
<% content_for :page_title do %>
  <h1 class="page-header"><%= @leader.name %></h1>
<% end %>

<%= render :partial => 'profile', locals: {leader: @leader} %>