config/routes.rb
Psp::Application.routes.draw do

  root to: 'states#index'

  resources :leaders

  resources :states do
    resources :leaders
    resource :calendar
    resources :subscriptions
  end

  match "/states/:id/:year/:month/:day/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/email", to: "states#email", as: "state_email"

  match "/states/:id/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"

  match "/states/:id/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/calendars/daily/:year/:month/:day", to: "states#show", as: "daily_calendar"
  match "/states/:id/calendars/weekly/:year/:month/:day", to: "states#show", as: "weekly_calendar"

  match "/states/:id/:year/:month/:day", to: "states#show", as: "state_date"

  mount Refinery::Core::Engine, :at => '/'

end

app/views/partials/_facebook_sdk.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

app/views/partials/_flash_messages.html.erb
      <% flash.each do |key, val| %>
        <div class="alert alert-<%= key %> offset3 span5">
          <button class="close" data-dismiss="alert">×</button>
          <strong><%= key.to_s.humanize %>.</strong>
          <%= val %>
        </div>
      <% end %>

app/views/partials/_footer.html.erb
<footer class="container-fluid">
<p class="lead">
  <%= link_to "Find Your State", "/states" %>
</p>
<hr />
<p>
  <strong>Copyright &copy; 2017 Public Servants' Prayer. All rights reserved.</strong>
</p>
<div class="row">
  <div class="offset2 span8 well">

    <hr />

    <div class="row">
      <div class="span4">
        <p style="padding-left:5em">
        Powered by the exellent data services of <a href="https://www.knowwho.com/" target="_blank">KnowWho.com</a>
        </p>
      </div>
      <div class="span4">
        <%= link_to image_tag("/assets/know-who-logo.jpg", alt: "KnowWho", style: "width:50%"), "https://www.knowwho.com/",  target: "_blank" %>
      </div>
    </div>
  </div>
</div>
</footer>

app/views/partials/_head.html.erb
  <head>
    <meta charset="utf-8">
    <% if usaprays? %>
      <title>USA Prays</title>
    <% else %>
      <title>Public Servants' Prayer</title>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>
    <%= stylesheet_link_tag  "application", :media => "all" %>
    <%= yield :html_head %>
  </head>

app/views/partials/_left_column_states.html.erb
    <ul class="nav nav-list">

      <% active = params[:controller] == "states" %>
      <%= state_nav_li("State Home", state_path(@state), 'home', active) %>

      <% active = params[:controller] == "leaders" %>
      <%= state_nav_li("State Leaders", state_leaders_path(@state), 'user', active) %>

      <% if false %>
      <% active = params[:controller] == "calendars" %>
      <%= state_nav_li("Prayer Calendar", state_calendars_path(@state), 'calendar', active) %>
      <% end %>

      <li class="nav-header">Prayer List</li>

      <% active = params[:id] == "daily" %>
      <%= state_nav_li("Subscribe Daily", state_subscription_path(@state, 'daily'), 'th', active) %>

      <% active = params[:id] == "weekly" %>
      <%= state_nav_li("Subscribe Weekly", state_subscription_path(@state, 'weekly'), 'align-justify', active) %>

    </ul>

    <div style="margin:3em 0">
      <%= image_tag "/assets/capitols/#{@state.code}-400.png" %>
    </div>

    <div style="margin:10px">
    <a href="https://twitter.com/<%= @state.twitter_handle %>" class="twitter-follow-button" data-show-count="false">Follow @mattrbarnes</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    </div>


    <div class="fb-like-box" data-href="<%= @state.facebook_url %>" data-width="225" data-show-faces="false" data-stream="false" data-header="false"></div>

    <br />

    <% if false %>
      <div class="fb-subscribe" data-href="https://www.facebook.com/pspindiana" data-show-faces="false" data-width="100"></div>
    <div style="overflow: hidden; border-right: 1px solid #d5d5d5;">
      <div class="fb-like-box" data-href="<%= @state.facebook_url %>" data-width="274" data-show-faces="true" data-stream="true" data-header="true"></div>
    </div>
  <% end %>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

     <%= link_to "Public Servants' Prayer", main_app.root_path, class: "brand" %>


      <div class="nav-collapse">
        <ul class="nav pull-right">

          <% css = "" %>
          <li class="<%= css %>"><%= link_to "Find Your State", "/states" %></li>

          <li class="<%= css %>"><%= link_to "Blog", "http://blog.publicservantsprayer.org/" %></li>

          <% css = params[:path] == "about" ? "active" : "" %>
          <li class="<%= css %>"><%= link_to "About", "http://blog.publicservantsprayer.org/about" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/partials/_right_column.html.erb
<p style="text-align:center">
  <%= image_tag "psp-logo-foundation.png" %>
</p>
<hr />
<blockquote class="">
  <p><em>I exhort therefore,
  that, first of all, supplications, prayers, intercessions, and giving of thanks, be made for all men;
  For kings, and for all that are in authority; that we may lead a quiet and peaceable life
  in all godliness and honesty.  For this is good and acceptable in the sight of God our Saviour;
  Who will have all men to be saved, and to come unto the knowledge of the truth.</em></p>
  <small><em>1 Timothy 2:1-4</em></small>
</blockquote>

<hr />
<hr />
<br />
<br />