config/routes.rb
Psp::Application.routes.draw do

  root to: 'states#index'

  resources :leaders

  resources :states do
    resources :leaders
    resource :calendar
    resources :subscriptions
  end

  match "/states/:id/:year/:month/:day/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"
  match "/states/:id/:year/:month/:day/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/email", to: "states#email", as: "state_email"

  match "/states/:id/calendars/daily/twitter", to: "states#twitter", as: "daily_twitter_feed"
  match "/states/:id/calendars/daily/facebook", to: "states#facebook", as: "daily_facebook_feed"

  match "/states/:id/calendars/daily/email", to: "states#email", as: "daily_email"
  match "/states/:id/calendars/daily/:year/:month/:day", to: "states#show", as: "daily_calendar"
  match "/states/:id/calendars/weekly/:year/:month/:day", to: "states#show", as: "weekly_calendar"

  match "/states/:id/:year/:month/:day", to: "states#show", as: "state_date"

  mount Refinery::Core::Engine, :at => '/'

end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  def index
    render layout: "application"
  end

  def show
    cookies[:state_code] = params[:id]
    @state = UsState.new(params[:id])
    @date = build_date
    @leaders = LeaderSelector.for_day(@state, @date)
    Rails.logger.error(@leaders)

    respond_to do |format|
      format.html
      format.rss { render :layout => false } #show.rss.builder
    end
  end

  def twitter
    @state = UsState.new(params[:id])
    @date = build_date
    @leaders = LeaderSelector.for_day(@state, @date)
    Rails.logger.error(@leaders)

    respond_to do |format|
      format.rss { render :layout => false } #twitter.rss.builder
    end
  end

  def facebook
    @state = UsState.new(params[:id])
    @date = build_date
    @leaders = LeaderSelector.for_day(@state, @date)
    Rails.logger.error(@leaders)

    respond_to do |format|
      format.rss { render :layout => false } #facebook.rss.builder
    end
  end

  def email
    @state = UsState.new(params[:id])
    @date = build_date
    @leaders = LeaderSelector.for_day(@state, @date)

    respond_to do |format|
      format.html { render :layout => false } 
      format.rss { render :layout => false } 
    end
  end

  private

    def build_date
      year = params[:year] || Time.current.to_date.year
      month = params[:month] || Time.current.to_date.month
      day = params[:day] || Time.current.to_date.day
      Date.new(year.to_i, month.to_i, day.to_i)
    end
end

app/helpers/states_helper.rb
module StatesHelper

  def leader_data_tr(leader_field, leader_label)
    unless leader_field.blank?
      str =  "<tr>"
      str += "<th>#{leader_label}</th>"
      str += "<td>#{leader_field}</td>"
      str += "</tr>"
      str.html_safe
    end
  end
end

app/views/states/_email_rss.html.erb
<table cellpadding="0" cellspacing="0" border="0" align="center">
  <tr>
    <td valign="top" style="text-align:center;!important;background-color: #ffffff;padding: 1em;margin: 1em">
      <h1 style="text-align:center;font-size:32px;color:#143e76 !important">Leaders Being Prayed For Today</h1>
      <h2 style="text-align:center;color:#333333 !important"><%= @date.strftime("%A, %B %-d, %Y") %></h2>
      <%= image_tag "http://publicservantsprayer.org/assets/capitols/#{@state.code}-400.png" %>
      <h3 style="text-align:center;font-size:38px;color:#700f16 !important;font-weight:bold;margin:0"><%= @state.name %></h3>
    </td>
  </tr>

  <% @leaders.each do |leader| %>
    <tr>
      <td valign="top" style="border:20px solid #ffffff !important;background-color: #F5F5F5;padding: 1em;margin: 1em">
        <%= render partial: "leaders/profile_email_rss.html.erb", 
          locals: { leader: leader } %>
      </td>
    </tr>
  <% end %>

  <tr>
    <td valign="top" style="text-align:center;!important;background-color: #ffffff;padding: 1em;margin: 1em">
      <%= link_to(image_tag("http://publicservantsprayer.org/assets/psp-logo-foundation.png", alt: "Public Servants' Prayer"), state_url(@state)) %>
    </td>
  </tr>
</table>

app/views/states/_member_pdf.pdf.erb
<div style="padding:10px">
  <%= image_tag "#{Rails.root}/public/#{member.photo_src}", style: "width:80px;float:left;padding-right:0" %>
  <div style="float:right;width:90px;font-size:8px;text-align:left">
    <h3 style="font-size:10px;margin:0"><%= member.name %></h3>
    <p style="color:#700f16;margin-top:0"><%= member.title.strip %></p>

    <dl>
    <dt>District</dt>
    <% unless member.residence.blank? %>
    <dd><%= member.residence %></dd>
    <% end %>
    <dd>(<%= member.district %>)</dd>
    </dl>

    <% unless member.religion.blank? %>
    <dl>
    <dt>Religion</dt>
    <dd><%= member.religion %></dd>
    </dl>
    <% end %>

    <% unless member.spouse.blank? %>
    <dl>
    <dt>Spouse</dt>
    <dd><%= member.spouse %></dd>
    </dl>
    <% end %>

    <% unless member.family.blank? %>
    <dl>
    <dt>Family</dt>
    <dd><%= member.family %></dd>
    </dl>
    <% end %>
  </div>
</div>
<div style="clear:both"></div>
<hr style="margin-top:1em" />

app/views/states/_region_button.html.erb
<div class="btn-group" style="position:absolute;<%= position %>">
  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
    <%= region.titlecase %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% UsState.send(region).each do |state| %>
      <li><%= link_to state.name, state_path(state) %></li>
    <% end %>
  </ul>
</div>

app/views/states/email.html.erb
 <!-- ***************************************************
********************************************************

HOW TO USE: Use these code examples as a guideline for formatting your HTML email. You may want to create your own template based on these snippets or just pick and choose the ones that fix your specific rendering issue(s). There are two main areas in the template: 1. The header (head) area of the document. You will find global styles, where indicated, to move inline. 2. The body section contains more specific fixes and guidance to use where needed in your design.

DO NOT COPY OVER COMMENTS AND INSTRUCTIONS WITH THE CODE to your message or risk spam box banishment :).

It is important to note that sometimes the styles in the header area should not be or don't need to be brought inline. Those instances will be marked accordingly in the comments.

********************************************************
**************************************************** -->

<!-- Using the xHTML doctype is a good practice when sending HTML email. While not the only doctype you can use, it seems to have the least inconsistencies. For more information on which one may work best for you, check out the resources below.

UPDATED: Now using xHTML strict based on the fact that gmail and hotmail uses it.  Find out more about that, and another great boilerplate, here: http://www.emailology.org/#1

More info/Reference on doctypes in email:
Campaign Monitor - http://www.campaignmonitor.com/blog/post/3317/correct-doctype-to-use-in-html-email/
Email on Acid - http://www.emailonacid.com/blog/details/C18/doctype_-_the_black_sheep_of_html_email_design
-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Your Message Subject or Title</title>
  <style type="text/css">

    /***********
    Originally based on The MailChimp Reset from Fabio Carneiro, MailChimp User Experience Design
    More info and templates on Github: https://github.com/mailchimp/Email-Blueprints
    http://www.mailchimp.com &amp; http://www.fabio-carneiro.com

    INLINE: Yes.
    ***********/
    /* Client-specific Styles */
    #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
    body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
    /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
    .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
    #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
    /* End reset */

    /* Some sensible defaults for images
    1. "-ms-interpolation-mode: bicubic" works to help ie properly resize images in IE. (if you are resizing them using the width and height attributes)
    2. "border:none" removes border when linking images.
    3. Updated the common Gmail/Hotmail image display fix: Gmail and Hotmail unwantedly adds in an extra space below images when using non IE browsers. You may not always want all of your images to be block elements. Apply the "image_fix" class to any image you need to fix.

    Bring inline: Yes.
    */
    img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
    a img {border:none;}
    .image_fix {display:block;}

    /** Yahoo paragraph fix: removes the proper spacing or the paragraph (p) tag. To correct we set the top/bottom margin to 1em in the head of the document. Simple fix with little effect on other styling. NOTE: It is also common to use two breaks instead of the paragraph tag but I think this way is cleaner and more semantic. NOTE: This example recommends 1em. More info on setting web defaults: http://www.w3.org/TR/CSS21/sample.html or http://meiert.com/en/blog/20070922/user-agent-style-sheets/

    Bring inline: Yes.
    **/
    p {margin: 1em 0;}

    /** Hotmail header color reset: Hotmail replaces your header color styles with a green color on H2, H3, H4, H5, and H6 tags. In this example, the color is reset to black for a non-linked header, blue for a linked header, red for an active header (limited support), and purple for a visited header (limited support).  Replace with your choice of color. The !important is really what is overriding Hotmail's styling. Hotmail also sets the H1 and H2 tags to the same size.

    Bring inline: Yes.
    **/
    h1, h2, h3, h4, h5, h6 {color: black !important;}

    h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

    h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
      color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
     }

    h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
      color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
    }

    /** Outlook 07, 10 Padding issue: These "newer" versions of Outlook add some padding around table cells potentially throwing off your perfectly pixeled table.  The issue can cause added space and also throw off borders completely.  Use this fix in your header or inline to safely fix your table woes.

    More info: http://www.ianhoar.com/2008/04/29/outlook-2007-borders-and-1px-padding-on-table-cells/
    http://www.campaignmonitor.com/blog/post/3392/1px-borders-padding-on-table-cells-in-outlook-07/

    H/T @edmelly

    Bring inline: No.
    **/
    table td {border-collapse: collapse;}

    /** Remove spacing around Outlook 07, 10 tables

    More info : http://www.campaignmonitor.com/blog/post/3694/removing-spacing-from-around-tables-in-outlook-2007-and-2010/

    Bring inline: Yes
    **/
    table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

    /* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email, bring your styles inline.  Your link colors will be uniform across clients when brought inline.

    Bring inline: Yes. */
    a {color: orange;}

    /* Or to go the gold star route...
    a:link { color: orange; }
    a:visited { color: blue; }
    a:hover { color: green; }
    */

    /***************************************************
    ****************************************************
    MOBILE TARGETING

    Use @media queries with care.  You should not bring these styles inline -- so it's recommended to apply them AFTER you bring the other stlying inline.

    Note: test carefully with Yahoo.
    Note 2: Don't bring anything below this line inline.
    ****************************************************
    ***************************************************/

    /* NOTE: To properly use @media queries and play nice with yahoo mail, use attribute selectors in place of class, id declarations.
    table[class=classname]
    Read more: http://www.campaignmonitor.com/blog/post/3457/media-query-issues-in-yahoo-mail-mobile-email/
    */
    @media only screen and (max-device-width: 480px) {

      /* A nice and clean way to target phone numbers you want clickable and avoid a mobile phone from linking other numbers that look like, but are not phone numbers.  Use these two blocks of code to "unstyle" any numbers that may be linked.  The second block gives you a class to apply with a span tag to the numbers you would like linked and styled.

      Inspired by Campaign Monitor's article on using phone numbers in email: http://www.campaignmonitor.com/blog/post/3571/using-phone-numbers-in-html-email/.

      Step 1 (Step 2: line 224)
      */
      a[href^="tel"], a[href^="sms"] {
            text-decoration: none;
            color: black; /* or whatever your want */
            pointer-events: none;
            cursor: default;
          }

      .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
            text-decoration: default;
            color: orange !important; /* or whatever your want */
            pointer-events: auto;
            cursor: default;
          }
    }

    /* More Specific Targeting */

    @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
      /* You guessed it, ipad (tablets, smaller screens, etc) */

      /* Step 1a: Repeating for the iPad */
      a[href^="tel"], a[href^="sms"] {
            text-decoration: none;
            color: blue; /* or whatever your want */
            pointer-events: none;
            cursor: default;
          }

      .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
            text-decoration: default;
            color: orange !important;
            pointer-events: auto;
            cursor: default;
          }
    }

    @media only screen and (-webkit-min-device-pixel-ratio: 2) {
      /* Put your iPhone 4g styles in here */
    }

    /* Following Android targeting from:
    http://developer.android.com/guide/webapps/targeting.html
    http://pugetworks.com/2011/04/css-media-queries-for-targeting-different-mobile-devices/  */
    @media only screen and (-webkit-device-pixel-ratio:.75){
      /* Put CSS for low density (ldpi) Android layouts in here */
    }
    @media only screen and (-webkit-device-pixel-ratio:1){
      /* Put CSS for medium density (mdpi) Android layouts in here */
    }
    @media only screen and (-webkit-device-pixel-ratio:1.5){
      /* Put CSS for high density (hdpi) Android layouts in here */
    }
    /* end Android targeting */
  </style>

  <!-- Targeting Windows Mobile -->
  <!--[if IEMobile 7]>
  <style type="text/css">

  </style>
  <![endif]-->

  <!-- ***********************************************
  ****************************************************
  END MOBILE TARGETING
  ****************************************************
  ************************************************ -->

  <!--[if gte mso 9]>
  <style>
    /* Target Outlook 2007 and 2010 */
  </style>
  <![endif]-->
</head>
<body style="background:white">

<%= render partial: "email_rss" %>

</body>
</html>
 

app/views/states/index.html.erb
<% content_for :page_title do %>
  <h1 class="page-header">Find Your State</h1>
<% end %>

<p class="lead">
You are invited to join us as we pray for three elected officials daily.  Use the map or select a region to find your leaders.
</p>

<div class="hidden-phone">
</div>

<div style="position:relative">

  <%= render :partial => 'map' %>

  <%= render :partial => 'region_button', 
    locals: {region: 'northeast', position: 'top:0;right:5%'} %>

  <%= render :partial => 'region_button', 
    locals: {region: 'midwest', position: 'top:0;right:40%'} %>

  <%= render :partial => 'region_button', 
    locals: {region: 'south', position: 'bottom:50%;right:5%'} %>

  <%= render :partial => 'region_button', 
    locals: {region: 'west', position: 'top:20%;left:0'} %>

</div>

<% if false %>
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <li class="active hidden-phone"><a href="#map" data-toggle="tab">Map</a></li>
    <li><a href="#northeast" data-toggle="tab">Northeast</a></li>
    <li><a href="#midwest" data-toggle="tab">Midwest</a></li>
    <li><a href="#south" data-toggle="tab">South</a></li>
    <li><a href="#west" data-toggle="tab">West</a></li>
  </ul>

  <div class="tab-content">
    <div class="hidden-phone tab-pane active" id="map">
      <%= render :partial => 'map' %>
    </div>
    <div class="tab-pane" id="northeast">
      <h2>States in the Northeast</h2>
      <ul class="nav nav-pills nav-stacked">
        <% UsState.northeast.each do |state| %>
          <li><%= link_to state.name, state_path(state) %></li>
        <% end %>
      </ul>
    </div>
    <div class="tab-pane" id="midwest">
      <h2>States in the Midwest</h2>
      <ul class="nav nav-pills nav-stacked">
        <% UsState.midwest.each do |state| %>
          <li><%= link_to state.name, state_path(state) %></li>
        <% end %>
      </ul>
    </div>
    <div class="tab-pane" id="south">
      <h2>States in the South</h2>
      <ul class="nav nav-pills nav-stacked">
        <% UsState.south.each do |state| %>
          <li><%= link_to state.name, state_path(state) %></li>
        <% end %>
      </ul>
    </div>
    <div class="tab-pane" id="west">
      <h2>States in the West</h2>
      <ul class="nav nav-pills nav-stacked">
        <% UsState.west.each do |state| %>
          <li><%= link_to state.name, state_path(state) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/states/show.html.erb
<%= auto_discovery_link_tag(:rss, "/states/#{params[:id]}/feed.rss") %>

<% content_for :page_title do %>
  <h1 class="page-header"><%= @state.name %></h1>
<% end %>

<div class="row-fluid">
  <h2 class="state-header">Leaders Being Prayed For Today</h2>
  <h3 class="date"><%= @date.strftime("%A, %B %-d, %Y") %></h3>
  <div class="">
    <% @leaders.each do |leader| %>
      <%= render :partial => 'leaders/profile', 
        formats: [:html], 
        locals: {leader: leader} %>
    <% end %>
  </div>
</div>

app/views/states/show.pdf.erb
<style>
table {
width:100%;
}
dl {
}
dt {
font-weight: bold;
}
dd {
margin-left: 1em;
}
ul {
padding-left: 1em;
}
</style>

<table>
<tr>
<% 7.times do |i| %>
  <% date = @sunday + i %>
  <td valign="top">
    <div style="padding:10px;text-align:center">
      <%= image_tag "#{Rails.root}/app/assets/images/psp-logo-tagline.png", style: "border:5px solid #9E4045;width:195" %>
      <h1 style="font-size:16px;font-style:italic;color:#700f16">Pray for Your Leaders<br /><%= @state.name %></h1>
      <h2 style="font-size:12px;color:#777"><%= date.strftime("%A, %B %-d, %Y") %></h2>
      <hr style="margin-top:1em"/>
      <%= render :partial => 'member_pdf', locals: {member: @state.member_zero(date)} %>
      <%= render :partial => 'member_pdf', locals: {member: @state.member_one(date)} %>
      <%= render :partial => 'member_pdf', locals: {member: @state.member_two(date)} %>
      <%= image_tag "#{Rails.root}/app/assets/images/publicservantsprayer-qr-code.png", style: "margin-top:1em;width: 100px" %>
      <h3 style="font-size:12px;color:navy">PublicServantsPrayer.org</h3>
      <div style="margin-top:1em;padding: 0.5em;color:#fff;background:#700f16"></div>
      <%= image_tag "#{Rails.root}/app/assets/images/cc-logo-611x137.png", style: "width: 180px" %>
    </div>
  </td>
<% end %>
</tr>
</table>